### ISSUE TITLE
Font customization

### ISSUE THREAD

**Issue by bit-garden** [termux/termux-float#11]
It seems the Termux:Style doesnt apply to Float. It can cause such inconsistencies as this. 

https://plus.google.com/photos/photo/106045239878311102993/6484175137703715138?icm=false&iso=true&sqid=101692629528551299417&ssid=017607d9-e204-4088-a861-4d5c9b9b80b9

**Comment by fornwall** [comment]
Thanks - this has been fixed in version 0.11 of the app, which has been released and should be available as an update for you shortly!

**Comment by Boruch-Baum** [comment]
It seems that this is broken again.
Android v9. Termux v0.95. Termux:Styling v0.28. Termux:Float v0.13
I've set the colors in termux to e-ink. It works in termux, but the colors in float remain white-on-black. Long-pressing on the float window allows for moving and resizing the window, but does not include the 'copy' or 'more' options to access Termux:Style from within Termux:Float.

**Comment by xeffyr** [comment]
> broken again

@Boruch-Baum Termux:Float [implements](https://github.com/termux/termux-float/blob/master/app/src/main/java/com/termux/window/TermuxFloatView.java#L103) only font settings. Colors config was never implemented for Float, you may open an issue for it.

**Comment by Boruch-Baum** [comment]
@xeffyr : Thanks. Will do that now
