### ISSUE TITLE
Is libtermux.so neccessary?

### ISSUE THREAD

**Issue by OffifialMITX** [termux/termux-float#18]
I've noticed that libtermux.so is located in both Termux and Termux:Float. Is thus really neccessary?

_Sent from my Moto E (4) Plus using [FastHub-Libre](https://github.com/thermatk/FastHub-Libre/)_

**Comment by xeffyr** [comment]
Necessary. Termux:Float isn't standalone. There is "termux-view" dependency:
```
implementation 'com.termux:terminal-view:0.50'
```
which depends on "terminal-emulator". It uses JNI so library is required.

Sources:
* https://github.com/termux/termux-app/tree/master/terminal-emulator
* https://github.com/termux/termux-app/tree/master/terminal-view
