### ISSUE TITLE
No line wrapping

### ISSUE THREAD

**Issue by alephalpha0** [termux/termux-float#24]
**Problem description**

When typing in a command that is longer than my termux:floats terminal width, the text keeps going on the same line where I am unable to view it.

**Steps to reproduce**

1. Launch termux:float
2. Type a rather long command e.g. `curl -LO https://raw.githubusercontent.com/alephalpha0/alephalpha0/master/README.md` 
3. Watch the text go past the window border.

**Expected behavior**

The main termux app, just like most terminals, wraps any text at the window border/terminal 2width and makes a new line. Expected termux:float to do the same behaviour.

**Additional information**

* Termux application version: termux:float 0.13 from F-DROID
* Android OS version: 10 with security patch June 1, 2020
* Device model: Samsung Galaxy A205U 

![Screenshot_20200810-050912_Vivaldi-01](https://user-images.githubusercontent.com/64208788/89772996-a97bd200-dac8-11ea-9752-403a4de722b6.jpeg)

**Comment by Grimler91** [comment]
It wraps as it should for me. You seem to have a custom PS1, what is it set to?

**Comment by alephalpha0** [comment]
Uhm, just `#`... No real idea how/why that came to be..
```
% echo $PS1 
%# 
% 
```

**Comment by Grimler91** [comment]
Nevermind, you are using zsh, that's why it's a '%'. 

In your screenshot you seem to be missing only two characters. Does it wrap if you write a very long line?

**Comment by alephalpha0** [comment]
I think it might be a mis-setting of the terminal width for termux:float...
Here's a screenshot of me typing out 
```
This is my incredibly long and not at all well thought out example in the floating terminal to prove my point. I think my terminal width is misset somewhere?
``
![Screenshot_20200810-092827_Vivaldi](https://user-images.githubusercontent.com/64208788/89793836-ec02d600-daeb-11ea-810b-83a2ac204954.png)
`

**Comment by xeffyr** [comment]
> I think it might be a mis-setting of the terminal width for termux:float...

Then it should be reproducible with any shell at default settings, with no plugins installed.

**Comment by xeffyr** [comment]
Bash:
![Screenshot_20200810-200729_Trebuchet](https://user-images.githubusercontent.com/25881154/89810225-6449b580-db45-11ea-8106-b1d8c7957311.png)

Zsh:
![Screenshot_20200810-200835_Trebuchet](https://user-images.githubusercontent.com/25881154/89810258-70ce0e00-db45-11ea-8400-c58b70b59516.png)

None of tested shells use "special" configuration or plug-ins.

I'll assume your issue happens due to configuration, specifically highlighting as it often causes issues with small terminal windows (not just in Termux!).
