### ISSUE TITLE
Need Help: Changing scope

### ISSUE THREAD

**Issue by dataminion** [termux/termux-float#3]
Is there a command or action that allows you to minimize or make the floating app no longer the point of focus?

Would really love to be able to switch between tasks without the overlay some times while keeping the session up.

**Comment by conrad-heimbold** [comment]
- to minimize / hide the floating widget, just tap on the notification for it. If you want to see the floating widget again, just tap on the notification again. 
- if you don't want to have focus on the widget, just tap scroll / slide anywhere else (e.g. next to it). 

Android is touch-oriented, keyboard controls are not very common.

**Comment by conrad-heimbold** [comment]
Could I help you? If yes, please close this issue.

**Comment by xeffyr** [comment]
Termux:Float supports customization in the following ways:

1. To change font size: **double tap** + up/down.
2. To change window size: **long tap** + pinch zooming (like in web browser).
