### ISSUE TITLE
Displays google play warning even though using F-droid version

### ISSUE THREAD

**Issue by wmartinmimi** [termux/termux-float#39]
Problem description

The float app shows the "google play store no longer supported" warning during opening, but both the Float and Main app is installed from F-droid.
This warning does not show when opening the Main app.

Steps to reproduce

when i open the float application, it will show automatically

Expected behavior

the google play warning should not be showing

Additional information

Termux application version: 
    Termux : 0.117
    Float : 0.14
Android OS version: Android 10
Device model: Redmi Note 8T

**Comment by Grimler91** [comment]
Could you share your output of `termux-info`?

**Comment by wmartinmimi** [comment]
![Screenshot_2021-10-10-18-04-14-438_com.sharpened.androidfileviewer.jpg](https://user-images.githubusercontent.com/82596011/136706035-749f2800-73cc-4520-964e-551886341afb.jpg)

**Comment by agnostic-apollo** [comment]
Closed by `termux-float` [v0.15.0](https://github.com/termux/termux-float/releases/tag/v0.15.0).
