### ISSUE TITLE
Package conflicts with an existing package

### ISSUE THREAD

**Issue by TostrStrudl** [termux/termux-float#47]
As the title says, I'm trying to install this plugin, but my OnePlus 8 with crDroid ROM won't let me. I have Termux installed (v0.118), and the only other plugin I have (had; just uninstalled it) is/was Termux:Widget. Any idea what could be causing this?

* Termux application version: v0.118.0
* Android OS version: 12.0
* Device model: IN2019 (OnePlus 8 5G UW)

**Comment by agnostic-apollo** [comment]
Install the app and all plugins from same source.

https://github.com/termux/termux-float#installation
