### ISSUE TITLE
Error installing from f-droid

### ISSUE THREAD

**Issue by roblabla** [termux/termux-float#6]
When installing from f-droid, I get the error "Failed to install due to an unknown error". I installed termux and termux-styling from f-droid.

In the logcat, I get the following error

```
04-24 19:44:27.073 14913 14913 W ZipFileCache: Open zip file:com.termux.window failed!
```

**Comment by fornwall** [comment]
Thanks! You can track the Termux issue at https://github.com/termux/termux-float/issues/4, and the root cause issue at F-Droid at https://gitlab.com/fdroid/fdroidserver/issues/288.

**Comment by tung256** [comment]
i just tried on the Mi 4k android box. same error. were you able to resolve this error?

**Comment by xeffyr** [comment]
@tung256 Ensure that Termux and all add-ons (like Termux:Float) are being installed from the same source, i.e. only from Play Store or only from F-Droid.
