### ISSUE TITLE
"Corrupt package" on Android 7.1

### ISSUE THREAD

**Issue by mission712** [termux/termux-float#7]
Hello, when I try to install Termux:Float on Android 7.1 via F-Droid, I get the following:
![screenshot_20170427-073729](https://cloud.githubusercontent.com/assets/14175669/25468144/6b5c64ee-2b1c-11e7-89b1-50bc948ecb56.png)
Why could this be? I tried both 0.8 and 0.9.

**Comment by fornwall** [comment]
Thanks for reporting!

It's an issue with F-Droid currently being tracked on their side at https://gitlab.com/fdroid/fdroidserver/issues/288 - there is not much we can on the Termux side except waiting for that issue to be solved.
