### ISSUE TITLE
Termux listed but not available on F-Droid

### ISSUE THREAD

**Issue by conspacer** [termux/termux-float#8]
Loving Termux so far... interested to try out the float addon but it returns "Download unsuccessful" from F-Droid. Its also not available at the link provided here.
Should I raise the issue with F-Droid directly?

**Comment by fornwall** [comment]
Hello and thanks!

It's an F-Droid problem - you can track the issue at https://gitlab.com/fdroid/fdroidserver/issues/288

**Comment by kernelzeroday** [comment]
It looks like they found some sort of work around, can you please try to fix this.
